#  Assignment 5

This assignment covers material on matrices, norms, condition numbers and eigensystems. The assignment is due by 5pm on Friday the 17th of April.

The breakdown of the marks is as follows:

Question 0 - [1 mark]  
Question 1 - [7 marks]  
Questino 2 - [6 marks]  
Question 3 - [7 marks]  
Question 4 - [9 marks]  

# Question 0

You should have saved this notebook to your ACM20030-Assignments folder. Now:
- commit the notebook to your local repository
- push the changes to the GitHub

In [1]:
import numpy as np
from numpy import linalg as la
np.set_printoptions(linewidth=200)  # This stops line wrapping of larger matrices

# Question 1 - practice manipulating arrays

This questions asks you write a few functions for manipulating arrays of data

## Q1 a

Write a function that checks if a given $n\times n$ matrix is symmetric. Use only loops and `.shape` function from numpy (do not use any other special numpy functions).

In [175]:
def SymCheck(matrix):
    a = matrix
    if(a.shape[0] != a.shape[1]):
        return "Input matrix is not a square matrix"
    i = 0
    while(i < a.shape[0]):
        j = 0
        while(j < a.shape[0]):
            if(a[i,j] != a[j,i]):
                return "Non-Symetric Matrix"
            j += 1
        i += 1
    return "Symmetric Matrix"

Test your function on the two matrices below

In [176]:
A1 = np.random.rand(5,5)
SymMatrix = (A + A.T)/2

In [177]:
SymCheck(A)

'Non-Symetric Matrix'

In [178]:
SymCheck(SymMatrix)

'Symmetric Matrix'

## Q1 b

Write a function to transpose a general $n\times n$ matrix. Do this by writing loops and not using any special functions like `np.transpose()`, `A.T`, or any functions from any other library.

In [205]:
def Transpose(matrix):
    a = matrix
    if(a.shape[0] != a.shape[1]):
        return "Input matrix is not a square matrix"    
    t = np.zeros(a.shape)
    i = 0 
    while(i < a.shape[0]):
        j = 0
        while(j < a.shape[0]):
            t[i,j] = a[j,i]
            j += 1
        i += 1
    return t

Check your code by transposing the below random matrix and checking that $A^T \neq A$ and $(A^T)^T - A = 0$

In [206]:
A2 = np.random.rand(6,6)

Transpose(A2) - A2 
# Not equal to the 0 matrix so therefor AT and A are not equal

array([[ 0.        ,  0.04309609, -0.10990824,  0.39077069,  0.51487483,  0.02018198],
       [-0.04309609,  0.        ,  0.22905011,  0.00071334, -0.38523   ,  0.13772033],
       [ 0.10990824, -0.22905011,  0.        , -0.22355884,  0.07990804, -0.48190806],
       [-0.39077069, -0.00071334,  0.22355884,  0.        , -0.29255427,  0.3350458 ],
       [-0.51487483,  0.38523   , -0.07990804,  0.29255427,  0.        , -0.30902936],
       [-0.02018198, -0.13772033,  0.48190806, -0.3350458 ,  0.30902936,  0.        ]])

In [204]:
Transpose(Transpose(A2)) - A2
# Is equal to the 0 matrix so therefor our code effectively transposes the matrix

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

## Q1c

Write a function that finds the maximum entry in a matrix (where the matrix does not need to be square). Do this by writing loops and not using any special functions like `np.max` or any functions from any other library.

In [368]:
def Max(matrix):
    a = matrix 
    m = 0
    i = 0
    if(a.shape == (len(a),)):
        while(i < a.shape[0]):
                if(a[i] > m):
                    m = a[i]
                i += 1
        return m
    while(i < a.shape[0]):
        j = 0
        while(j < a.shape[0]):
            if(a[i,j] > m):
                m = a[i,j]
            j += 1
        i += 1
    return m

Check your result by comparing to `np.max(A)` for the below random matrix

In [214]:
A3 = np.random.rand(4,5)

print(A3)

[[0.14520227 0.32252394 0.59421047 0.94711632 0.04440615]
 [0.92153465 0.69039914 0.05415032 0.9604868  0.12570734]
 [0.79038208 0.3933665  0.4095649  0.14424956 0.27710143]
 [0.93571399 0.62511933 0.91614178 0.54900396 0.60643804]]


In [215]:
Max(A3)
# We can clearly see that this value is the largest element in our matrix

0.9604868023871663

# Question 2:  matrix norms

In the lectures we focused on the $L^2$-norm. We also briefly mentioned the $L^1$ and $L^\infty$ norm. Let's look at calculating those as well for a general $m\times n$ matrix.

# Q2a

The $L^1$ norm is given by

$$ \lVert A \rVert_1 = \max_j \sum^m_{i=1} |a_{ij}| $$

i.e., it is the max of the sums of the absolute values of each column. Write a function that computes the $L^1$-norm using only loops. The function should use no special numpy functions except `np.abs()`.

In [384]:
def Norm(matrix):
    a = matrix
    j = 0
    i = 0
    e = np.zeros(a.shape[1])
    while(j < a.shape[1]):
        i = 0
        mi = 0
        while(i < a.shape[0]):
            mi += np.abs(a[i,j])
            i += 1
        e[j] = mi
        j += 1
    return Max(e)

Check your result against NumPy's `la.norm(A,1)` function for the following random matrix

In [385]:
A4 = np.random.rand(3,4)

In [386]:
la.norm(A4,1)

2.5723887260342684

In [387]:
Norm(A4)

2.5723887260342684

## Q2b

The $L^\infty$ norm is given by 

$$\lVert A \rVert_\infty = \max_i \sum_{j=1}^n |a_{ij}|$$

i.e., it is the max of the sums of the absolute values of each row. Write a function that computes the $L^\infty$-norm using only loops and no special numpy functions.

In [388]:
def NormInf(matrix):
    a = matrix
    j = 0
    i = 0
    e = np.zeros(a.shape[0])
    while(i < a.shape[0]):
        j = 0
        mi = 0
        while(j < a.shape[1]):
            mi += np.abs(a[i,j])
            j += 1
        e[i] = mi
        i += 1
    return Max(e)

Check your result against NumPy's `la.norm(A,np.inf)` function for the following random matrix

In [389]:
A5 = np.random.rand(3,4)
la.norm(A5,np.inf)

2.260752099526049

In [390]:
NormInf(A5)

2.260752099526049

# Question 3: ill-conditions systems of equations

In this question you can use any of NumPy's functions.

## Q3a

Which of the following three matrices, $A1, A2, A3$, are ill-conditioned. State the reason for your conclusion.

In [46]:
A1 = np.array([[0.988746460106, 0.351486109477, 0.024911477532, 0.384039749683],
       [0.282104657306, 0.239884151775, 0.36170151991 , 0.903082266861],
       [0.59333290915 , 0.637178863968, 0.241229214635, 0.685595037901],
       [0.013591747828, 0.917926970364, 0.458689093885, 0.157821121254]])

A2 = np.array([[ 2.852416473483e-01,  3.803483118694e-01,  2.697704226632e-01,  6.810611849029e-01],
       [ 6.622827828376e-01,  6.447943415836e-01,  4.387842058829e-01,  1.530575702376e+00],
       [ 3.672130860703e-01,  8.309522079704e-01,  9.975487474007e-01,  5.678296337101e-01],
       [ 4.036490000599e-01,  6.865978225967e-06,  8.788095913773e-01, -7.150472427928e-02]])

A3 = np.array([[0.131923621844, 0.245316154195, 0.732362341613, 0.957047891764],
       [0.91290446184 , 0.512312007959, 0.391938831444, 0.092509684772],
       [0.648708523652, 0.608576675797, 0.576773587276, 0.065385122929],
       [0.502955480393, 0.084082960221, 0.659487390444, 0.662958739412]])

# Q3b

With $b = [1,2,3,4]$ and $\delta b = [0.1,0,0,0]$ for $A2$ and $A3$ calculate the percentage change in $x$ due to a small change in $b$, i.e., calculate 

$$100\times\frac{\lVert \delta x_i\rVert_2}{\lVert x_i \rVert_2}\quad\text{and}\quad 100\times\frac{\lVert \delta b\rVert_2}{\lVert b \rVert_2}$$

where $(x_i+\delta x_i)  = A_i^{-1}(b+\delta b)$ and $i\in\{2,3\}$.

Which system of equations is more sensitive to small changes in $b$? How could you have guessed this from the answer to the Q3a?

In [10]:
# Answer here
#

# Question 4: eigensystems

In this question we look at finding eigenvalues and eigenvectors

## Q4a

You may use any of NumPy's functions for this sub-question.

Find the eigenvalues and eigenvectors for the below matrix. Print out the eigenvalues sorted by descending value and explicitly show that eigenvalues/eigenvector pairs satisfy $Ax = \lambda x$.

In [50]:
A = np.array([[1,4,5],[4,5,4],[6,7,9]])

# Q4b

Without using NumPy's `la.eig()` (or similar functions), find the 4 eigenvalues and eigenvectors of the following matrix. Hint: Use the power method for the max eigenvalue (given below in `MaxEigenvalue`), the power method applied to the inverse for the smallest eigenvalue, and apply Hotelling's deflation twice to find the second and third eigenvalues/eigenvectors.

In [52]:
A = np.array([[1.935052353404, 0.887037260957, 1.534235483277, 1.370691224125],
       [0.887037260957, 0.81275989158 , 0.610238622918, 0.999150521052],
       [1.534235483277, 0.610238622918, 1.562260333538, 1.007843062517],
       [1.370691224125, 0.999150521052, 1.007843062517, 1.813258814483]])

In [53]:
def MaxEigenvalue(A, err):
    (m,n) = A.shape
    if(m != n):
        print("Matrix must be square")
        return
    x = np.random.rand(m)
    
    lam = 0.1
    lamprev = 1
    while np.abs(1-lam/lamprev) > err:
        p = np.dot(A,x)
        lamprev = lam
        lam = np.max(p)
        x = p/lam
        
    x = x/la.norm(x)
    return (lam,x)

Check your answers against Numpy's results from `la.eig(A)`